### ISSUE TITLE
Broadcast causes stop

### ISSUE THREAD

**Issue by xBigG** [rizaumami/tdcliBot#4]
If you run !broadcast the bot stops.

**Comment by rizaumami** [comment]
Fixed on [this commit](https://github.com/rizaumami/tdcliBot/commit/2a2dae01ce03394a35aaa4bbea4fa4f982f12702).

This commit also changed local `tdcli.lua` to `tdcli.lua` from luarocks.
It's better to reinstalled `tdcliBot` (using `tdcliBot install`) so dependencies will automatically resolved.
