### ISSUE TITLE
Hello i just wanna know how to set my own commands name 

### ISSUE THREAD

**Issue by kensukekita** [rizaumami/tdcliBot#5]
Hello i just wanna know how to set my own commands name 
for example how to call to !gban with !stupid or !ban

**Comment by rizaumami** [comment]
`tdcliBot` have no alias mecanism, so you have tou manually edit the relevant plugins.  
`gban` command is on `banhammer.lua`.

**Comment by kensukekita** [comment]
oh okay thanks bro!
