### ISSUE TITLE
i got an error when trying to gban 

### ISSUE THREAD

**Issue by kensukekita** [rizaumami/tdcliBot#6]
msg matches:    ^[/!#](gban) (%d+)$
Preprocess      channels
Preprocess      whitelist
Preprocess      groupmanager
 *** 1490992752.000000 lua: bot/plugins/banhammer.lua:58: attempt to concatenate local 'user_id' (a nil value)

with ban i get 

msg matches:    ^[/!#](ban) (.*)$
msg matches:    ^[/!#](ban) (%d+)$
Preprocess      channels
Preprocess      whitelist
Preprocess      groupmanager
 *** 1490993155.000000 lua: .luarocks/share/lua/5.2/redis.lua:380: redis error: ERR wrong number of arguments for 'hexists' command

 *** 1490993155.000000 lua: .luarocks/share/lua/5.2/redis.lua:380: redis error: ERR wrong number of arguments for 'hexists' command

and on another server with gban

Preprocess      channels
Preprocess      whitelist
Preprocess      groupmanager
msg matches:    ^[/!#](gban) (%d+)$
 *** 1490994207.000000 lua: .luarocks/share/lua/5.2/redis.lua:380: redis error: ERR wrong number of arguments for 'hexists' command

**Comment by kensukekita** [comment]
i think my redis is too old updating...

still the same errors

**Comment by rizaumami** [comment]
@kensukekita  
Thank you, this is a bug. I've fixed it in [this commit](https://github.com/rizaumami/tdcliBot/commit/485715843075a7e0016ae9e51477f835776bc7ef).

**Comment by kensukekita** [comment]
bro i started my bot and i got this after modifying config.lua to add another sudoer

[-3][t 0][1491072589.927760124][FileManager.cpp:1436][!FileLoadManager] Can't register local file after download: [Error : 0 : File was modified]
[-3][t 0][1491072590.228463650][FileManager.cpp:1436][!FileLoadManager] Can't register local file after download: [Error : 0 : File was modified]
[-3][t 0][1491072590.236560822][FileManager.cpp:1436][!FileLoadManager] Can't register local file after download: [Error : 0 : File was modified]
[-3][t 0][1491072590.244729042][FileManager.cpp:1436][!FileLoadManager] Can't register local file after download: [Error : 0 : File was modified]
[-3][t 0][1491072590.252766132][FileManager.cpp:1436][!FileLoadManager] Can't register local file after download: [Error : 0 : File was modified]
[-3][t 0][1491072590.260740519][FileManager.cpp:1436][!FileLoadManager] Can't register local file after download: [Error : 0 : File was modified]
[-3][t 0][1491072590.269023418][FileManager.cpp:1436][!FileLoadManager] Can't register local file after download: [Error : 0 : File was modified]
[-3][t 0][1491072590.276040316][FileManager.cpp:1436][!FileLoadManager] Can't register local file after download: [Error : 0 : File was modified]
[-3][t 0][1491072590.285478830][FileManager.cpp:1436][!FileLoadManager] Can't register local file after download: [Error : 0 : File was modified]
[-3][t 0][1491072590.292623281][FileManager.cpp:1436][!FileLoadManager] Can't register local file after download: [Error : 0 : File was modified]
[-3][t 0][1491072590.301320553][FileManager.cpp:1436][!FileLoadManager] Can't register local file after download: [Error : 0 : File was modified]

**Comment by rizaumami** [comment]
[Read the wiki](https://github.com/rizaumami/tdcliBot/wiki/Sudo#sudo-management).
You mostly no need to manually edit the config file.

I'm closing this thread as initial issue was resolved.
