### ISSUE TITLE
start command does not work

### ISSUE THREAD

**Issue by kensukekita** [rizaumami/tdcliBot#7]
i updated my installation but now it doesn't  works
also deleted it and redownloaded this repo but still not working when i write ./tdcliBot start
it just do nothing
root@ip-172-31-62-202:/var/www/html/botc/tdcliBot# ./tdcliBot start
root@ip-172-31-62-202:/var/www/html/botc/tdcliBot#

also i try to run it as sudo but it's the same

**Comment by rizaumami** [comment]
Cannot help you with this. It's works in my machine.
Make sure you follow the installation steps correctly.

**Comment by kensukekita** [comment]
yes sorry was my server
